<a href="https://colab.research.google.com/github/H0lyDiv3r/spam-classification/blob/main/emailSpamClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Load the dataset ('https://www.kaggle.com/datasets/jackksoncsie/spam-email-dataset')

# importing dataset


In [1]:
import pandas as pd

df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df['Category'] = df['Category'].map({"ham":0,"spam":1})
df

Category                                            Message
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0               Will ü b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

# import nltk

In [14]:
import nltk

nltk.download("popular")


[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nlt

True

In [15]:
df['Category'].value_counts()

0    4825
1     747
Name: Category, dtype: int64

# tokenize and lemmatize

In [16]:
from nltk.corpus import stopwords

def tokenizer(text):

  tokenize = nltk.RegexpTokenizer(r'\w+')
  tokenized = tokenize.tokenize(text)

  lower_case = [word.lower() for word in tokenized]

  lemmatizer = nltk.stem.WordNetLemmatizer()
  lemmatized = [lemmatizer.lemmatize(word) for word in lower_case]

  stop_words = set(stopwords.words('english'))
  useful_tokens = [word for word in lower_case if word not in stop_words]

  return useful_tokens

# Data set preparation

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = df['Message']
y = df['Category']

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=True,test_size=0.2)


In [19]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [20]:
X_train.iloc[0]

"Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?"

#Feature extraction

In [21]:
token_counter = {}


for message in X_train:
  message_as_token = tokenizer(message)

  for token in message_as_token:
    if token in token_counter:
      token_counter[token] +=1
    else:
      token_counter[token] = 1


In [22]:
len(token_counter)


7608

In [23]:
def keep_token(processed_token,threshold):
  if processed_token not in token_counter:
    return False
  else:
    return token_counter[processed_token] > threshold

In [24]:
keep_token("cash",100)

False

In [25]:
features = set()

for token in token_counter:
  if keep_token(token,50):
    features.add(token)

features

{'1',
 '150p',
 '2',
 '3',
 '4',
 '5',
 'already',
 'also',
 'amp',
 'anything',
 'ask',
 'b',
 'babe',
 'back',
 'c',
 'call',
 'cant',
 'care',
 'cash',
 'claim',
 'com',
 'come',
 'contact',
 'cos',
 'customer',
 'da',
 'day',
 'dear',
 'dont',
 'e',
 'even',
 'every',
 'feel',
 'find',
 'first',
 'free',
 'get',
 'give',
 'go',
 'going',
 'good',
 'got',
 'great',
 'gt',
 'gud',
 'happy',
 'help',
 'hey',
 'hi',
 'home',
 'hope',
 'im',
 'k',
 'keep',
 'know',
 'last',
 'later',
 'let',
 'life',
 'like',
 'lol',
 'lor',
 'love',
 'lt',
 'make',
 'meet',
 'message',
 'min',
 'miss',
 'mobile',
 'morning',
 'msg',
 'much',
 'n',
 'need',
 'new',
 'night',
 'nokia',
 'number',
 'oh',
 'ok',
 'one',
 'phone',
 'pick',
 'please',
 'pls',
 'prize',
 'r',
 'really',
 'reply',
 'right',
 'said',
 'say',
 'see',
 'send',
 'sent',
 'something',
 'sorry',
 'still',
 'stop',
 'sure',
 'take',
 'tell',
 'text',
 'thanks',
 'think',
 'time',
 'today',
 'told',
 'tomorrow',
 'txt',
 'u',
 'uk',
 

In [26]:
features = list(features)
print(features)

['new', 'prize', 'miss', 'morning', 'something', 'gt', 'pls', 'win', 'one', 'right', 'urgent', 'told', 'said', 'e', 'ask', 'already', 'yeah', 'customer', '3', 'feel', 'got', 'yes', 'find', 'care', 'b', 'time', 'still', 'anything', 'claim', 'us', 'da', 'going', 'think', 'really', 'text', 'gud', 'help', 'sorry', 'com', 'ok', 'life', 'please', '2', 'uk', 'cos', 'make', 'wat', 'r', 'ü', 'tomorrow', 'babe', 'sent', 'know', 'im', 'free', 'even', '1', 'send', 'stop', 'k', '5', 'love', 'see', 'phone', 'lor', 'back', 'cash', 'msg', 'good', 'c', 'number', 'like', 'dont', 'tell', 'happy', 'say', 'night', 'home', 'would', 'give', 'come', 'min', 'go', 'txt', 'work', '150p', 'pick', 'let', 'contact', 'keep', 'way', '4', 'sure', 'meet', 'call', 'well', 'thanks', 'amp', 'want', 'today', 'take', 'message', 'dear', 'later', 'hi', 'ur', 'mobile', 'day', 'get', 'hey', 'need', 'reply', 'hope', 'lt', 'much', 'www', 'nokia', 'first', 'last', 'u', 'lol', 'cant', 'n', 'also', 'week', 'oh', 'great', 'every']


# Word bag generation

In [27]:
token_index_mapping = {t:i for t,i in zip(features,range(len(features)))}
token_index_mapping

{'new': 0,
 'prize': 1,
 'miss': 2,
 'morning': 3,
 'something': 4,
 'gt': 5,
 'pls': 6,
 'win': 7,
 'one': 8,
 'right': 9,
 'urgent': 10,
 'told': 11,
 'said': 12,
 'e': 13,
 'ask': 14,
 'already': 15,
 'yeah': 16,
 'customer': 17,
 '3': 18,
 'feel': 19,
 'got': 20,
 'yes': 21,
 'find': 22,
 'care': 23,
 'b': 24,
 'time': 25,
 'still': 26,
 'anything': 27,
 'claim': 28,
 'us': 29,
 'da': 30,
 'going': 31,
 'think': 32,
 'really': 33,
 'text': 34,
 'gud': 35,
 'help': 36,
 'sorry': 37,
 'com': 38,
 'ok': 39,
 'life': 40,
 'please': 41,
 '2': 42,
 'uk': 43,
 'cos': 44,
 'make': 45,
 'wat': 46,
 'r': 47,
 'ü': 48,
 'tomorrow': 49,
 'babe': 50,
 'sent': 51,
 'know': 52,
 'im': 53,
 'free': 54,
 'even': 55,
 '1': 56,
 'send': 57,
 'stop': 58,
 'k': 59,
 '5': 60,
 'love': 61,
 'see': 62,
 'phone': 63,
 'lor': 64,
 'back': 65,
 'cash': 66,
 'msg': 67,
 'good': 68,
 'c': 69,
 'number': 70,
 'like': 71,
 'dont': 72,
 'tell': 73,
 'happy': 74,
 'say': 75,
 'night': 76,
 'home': 77,
 'would': 78

In [28]:
import numpy as np


In [29]:
def message_to_vector_count(message):

  count_vector = np.zeros(len(features))

  processed_tokens = tokenizer(message)

  for token in processed_tokens:
    if token not in features:
      continue
    index = token_index_mapping[token]
    count_vector[index] +=1
  return count_vector


In [30]:
message_to_vector_count(X_train[2])

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
X_train[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

# Data preparation

In [32]:
X_train = pd.DataFrame(data = [message_to_vector_count(x) for x in X_train])

In [33]:
X_test = pd.DataFrame(data = [message_to_vector_count(x) for x in X_test])

In [34]:
X_train

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4452  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4453  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4454  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
4455  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  2.0  0.0   
4456  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      121  122  123  124  125  126  127  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
4452  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4453  0.0  0.0  0.0  0.0  2.0  0.0  0.0  
4454  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4455  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4456  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[4457 rows x 128 columns]

#

# Trainig

In [35]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier()

In [36]:
y_train

1642    0
2899    0
480     0
3485    0
157     0
       ..
905     0
5192    0
3980    0
235     1
5157    0
Name: Category, Length: 4457, dtype: int64

In [37]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

# Prediction

In [38]:
pred = classifier.predict(X_test)

In [39]:
pred

array([0, 0, 0, ..., 0, 0, 0])

# Conclusion

In [40]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [41]:
accuracy_score(y_test,pred)

0.9704035874439462

In [42]:
confusion_matrix(y_test,pred)

array([[950,  18],
       [ 15, 132]])

In [43]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       968
           1       0.88      0.90      0.89       147

    accuracy                           0.97      1115
   macro avg       0.93      0.94      0.94      1115
weighted avg       0.97      0.97      0.97      1115

